// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuB9lprwAiPAEavZ2hojzFNrHMbqE7Plg',
    appId: '1:686088182609:web:c8e429549b1e321af65170',
    messagingSenderId: '686088182609',
    projectId: 'mtn-app-eca99',
    authDomain: 'mtn-app-eca99.firebaseapp.com',
    storageBucket: 'mtn-app-eca99.appspot.com',
    measurementId: 'G-CS12KJQZ7C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzWlccCeuyjPPN1W-mgOwRtfcZr8Uuksc',
    appId: '1:686088182609:android:c2feebb2d7f38455f65170',
    messagingSenderId: '686088182609',
    projectId: 'mtn-app-eca99',
    storageBucket: 'mtn-app-eca99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6dDYk61T4UhKf8nQQCOxweBCo4TwbMBU',
    appId: '1:686088182609:ios:46e806b2cce824bbf65170',
    messagingSenderId: '686088182609',
    projectId: 'mtn-app-eca99',
    storageBucket: 'mtn-app-eca99.appspot.com',
    iosBundleId: 'com.example.mtnApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6dDYk61T4UhKf8nQQCOxweBCo4TwbMBU',
    appId: '1:686088182609:ios:46e806b2cce824bbf65170',
    messagingSenderId: '686088182609',
    projectId: 'mtn-app-eca99',
    storageBucket: 'mtn-app-eca99.appspot.com',
    iosBundleId: 'com.example.mtnApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuB9lprwAiPAEavZ2hojzFNrHMbqE7Plg',
    appId: '1:686088182609:web:1a3572d7057ab244f65170',
    messagingSenderId: '686088182609',
    projectId: 'mtn-app-eca99',
    authDomain: 'mtn-app-eca99.firebaseapp.com',
    storageBucket: 'mtn-app-eca99.appspot.com',
    measurementId: 'G-0508G40YMJ',
  );

}